// <auto-generated />
namespace TestApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class initmigr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initmigr));
        
        string IMigrationMetadata.Id
        {
            get { return "201303200228281_initmigr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
