// <auto-generated />
namespace TestApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class seedData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seedData));
        
        string IMigrationMetadata.Id
        {
            get { return "201303200353480_seedData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
